swagger: '2.0'
info:
  description: Swagger doc for /api/server/hpdb/sensors
  title: Swagger doc for /api/server/hpdb/sensors
  version: 1.0.0
paths:
  /api/server/hpdb/sensors:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  HPDB_HSC1_VIN_VOLT_V:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  HPDB_HSC1_VOUT_VOLT_V:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  HPDB_HSC1_CURR_A:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  HPDB_HSC1_PWR_W:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  HPDB_HSC1_TEMP_C:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  HPDB_HSC2_VIN_VOLT_V:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  HPDB_HSC2_VOUT_VOLT_V:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  HPDB_HSC2_CURR_A:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  HPDB_HSC2_PWR_W:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  HPDB_HSC2_TEMP_C:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
