swagger: '2.0'
info:
  description: Swagger doc for /api/server/mezz1/sensors
  title: Swagger doc for /api/server/mezz1/sensors
  version: 1.0.0
paths:
  /api/server/mezz1/sensors:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  NIC1_MEZZ1_TEMP_C:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  NIC1_MEZZ1_P3V3_VOLT_V:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  NIC1_MEZZ1_P12V_CURR_A:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  NIC1_MEZZ1_P12V_PWR_W:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
