swagger: '2.0'
info:
  description: Swagger doc for /api/sys/presence/pim
  title: Swagger doc for /api/sys/presence/pim
  version: 1.0.0
paths:
  /api/sys/presence/pim:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  pim1:
                    type: string
                    pattern: ^[0-9]+$
                  pim2:
                    type: string
                    pattern: ^[0-9]+$
                  pim3:
                    type: string
                    pattern: ^[0-9]+$
                  pim4:
                    type: string
                    pattern: ^[0-9]+$
                  pim5:
                    type: string
                    pattern: ^[0-9]+$
                  pim6:
                    type: string
                    pattern: ^[0-9]+$
                  pim7:
                    type: string
                    pattern: ^[0-9]+$
                  pim8:
                    type: string
                    pattern: ^[0-9]+$
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
