swagger: '2.0'
info:
  description: Swagger doc for /api/server/hgx/fruid
  title: Swagger doc for /api/server/hgx/fruid
  version: 1.0.0
paths:
  /api/server/hgx/fruid:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  Usage:
                    type: string
                  '[field]':
                    type: string
                  e.g., fruid-util fru1 --modify --BMD "$( date +%s -d "2018-01-01 17:
                    type: string
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
