swagger: '2.0'
info:
  description: Swagger doc for /api/server/hgx/sensors
  title: Swagger doc for /api/server/hgx/sensors
  version: 1.0.0
paths:
  /api/server/hgx/sensors:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                format: nullable
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
