swagger: '2.0'
info:
  description: Swagger doc for /api/server/scm/sensors
  title: Swagger doc for /api/server/scm/sensors
  version: 1.0.0
paths:
  /api/server/scm/sensors:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  SCM_P12V_VOLT_V:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCM_P5V_VOLT_V:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCM_P3V3_VOLT_V:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCM_P2V5_VOLT_V:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCM_P1V8_VOLT_V:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCM_PGPPA_VOLT_V:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCM_P1V2_VOLT_V:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCM_P1V0_VOLT_V:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  SCM_INLET_TEMP_C:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
