swagger: '2.0'
info:
  description: Swagger doc for /api/sys/sensors
  title: Swagger doc for /api/sys/sensors
  version: 1.0.0
paths:
  /api/sys/sensors:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: array
                items:
                  type: object
                  additionalProperties: false
                  properties:
                    name:
                      type: string
                    Adapter:
                      type: string
                    ADC_1V8_MON:
                      type: string
                    ADC_3V3_MON:
                      type: string
                    ADC_1V2_MON:
                      type: string
                    ADC_2V5_MON:
                      type: string
                    ADC_1V0_MON:
                      type: string
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
