swagger: '2.0'
info:
  description: Swagger doc for /api/sled/mb/sensors
  title: Swagger doc for /api/sled/mb/sensors
  version: 1.0.0
paths:
  /api/sled/mb/sensors:
    get:
      produces:
      - application/json
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Information:
                type: object
                additionalProperties: false
                properties:
                  EP_MB_FAN0_TACH_I:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_FAN0_TACH_O:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_FAN0_VOLT:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_FAN0_CURR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_FAN1_TACH_I:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_FAN1_TACH_O:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_FAN1_VOLT:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_FAN1_CURR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_FAN2_TACH_I:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_FAN2_TACH_O:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_FAN2_VOLT:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_FAN2_CURR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_FAN3_TACH_I:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_FAN3_TACH_O:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_FAN3_VOLT:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_FAN3_CURR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_ADC_P12V_AUX:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_ADC_P3V3_STBY:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_ADC_P5V_STBY:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_ADC_P12V_1:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_ADC_P12V_2:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_ADC_P3V3:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_ADC_P3V_BAT:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_SENSOR_INLET:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_SENSOR_INLET_REMOTE:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_SENSOR_OUTLET:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_SENSOR_OUTLET_REMOTE:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_SENSOR_PAX01_THERM:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_SENSOR_PAX0_THERM:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_SENSOR_PAX1_THERM:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_SENSOR_PAX23_THERM:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_SENSOR_PAX2_THERM:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_SENSOR_PAX3_THERM:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_SWITCH_PAX0_DIE_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_SWITCH_PAX1_DIE_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_SWITCH_PAX2_DIE_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_SWITCH_PAX3_DIE_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P0V8_VDD0_VIN:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P0V8_VDD0_VOUT:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P0V8_VDD0_CURR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P0V8_VDD0_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P0V8_VDD1_VIN:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P0V8_VDD1_VOUT:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P0V8_VDD1_CURR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P0V8_VDD1_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P0V8_VDD2_VIN:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P0V8_VDD2_VOUT:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P0V8_VDD2_CURR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P0V8_VDD2_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P0V8_VDD3_VIN:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P0V8_VDD3_VOUT:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P0V8_VDD3_CURR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P0V8_VDD3_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P1V0_AVD0_VIN:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P1V0_AVD0_VOUT:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P1V0_AVD0_CURR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P1V0_AVD0_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P1V0_AVD1_VIN:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P1V0_AVD1_VOUT:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P1V0_AVD1_CURR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P1V0_AVD1_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P1V0_AVD2_VIN:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P1V0_AVD2_VOUT:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P1V0_AVD2_CURR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P1V0_AVD2_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P1V0_AVD3_VIN:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P1V0_AVD3_VOUT:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P1V0_AVD3_CURR:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
                  EP_MB_VR_P1V0_AVD3_TEMP:
                    type: object
                    additionalProperties: false
                    properties:
                      value:
                        type: string
              Actions:
                type: array
                items:
                  type: string
              Resources:
                type: array
                items:
                  type: string
